### ISSUE TITLE
Problem with radio buttons

### ISSUE THREAD

**Issue by BobbyBorisov** [Lupennat/nova-nested-many#20]
Hello, 

I think I stumbled on a problem with radio fields, I am trying to use this package https://github.com/Muetze42/nova-radio-field and put it in a 1 level nested resource. and basically when I make 2 child resources and try to select a value in the radio field of the first child I have no problem but when I go and select the radio from the second child resource it deselect the first one. 

Additionally when I try to click just on the text of the radio button (on the second child) it redirects me back to the first child (scrolls up) There seem to be duplicated ids for the fields, but not sure if its related or intentional from your side.

I have used similar nested form package - nova-nested-form where your package is based from and they have for example such input ids -> `resource[0][foo]` and `resource[1][foo]` for two children. you seem to create it as `foo-resource-text-field` for both children.

**Comment by Lupennat** [comment]
nova-radio-field package generate a name for each radio button, this name is not unique because does not use formUniqueId, but only the field attribute.
nova-nested-many is different from other similar packages, because it does not manipulate any field attribute.
https://github.com/Muetze42/nova-radio-field/issues/27

**Comment by Lupennat** [comment]
[PR opened](https://github.com/Muetze42/nova-radio-field/pull/28)
